### ISSUE TITLE
"You do not have permission to update this wiki." error message when browsing Wiki

### ISSUE THREAD

**Issue by kerkhofsd** [Acosix/alfresco-utility#10]
I am able to access the Wiki of this project and see an overview of all topics. Navigating to a specific topic (e.g. https://github.com/Acosix/alfresco-utility/wiki/Subsystem-Properties) doesn't work and results in error message: 

> You do not have permission to update this wiki.

Do (some of) these sub-pages have maybe restricted visibility?

**Comment by AFaust** [comment]
It just means that that particular page does not exist (intended to be written, but did not get around to it), and GitHub automatically attempted to open in edit mode, which is not valid for you..

**Comment by kerkhofsd** [comment]
Aha, I see. It was not clear to me that is work to be done. 
Might be a good idea to add a small remark for that to the overview? 

Thanks for the feedback.
