### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by maxodoble** [Acosix/alfresco-utility#11]
hi,

trying to build from master branch:

`mvn clean install`

getting this error:

`[ERROR] Failed to execute goal org.codehaus.mojo:findbugs-maven-plugin:3.0.5:findbugs (findbugs) on project de.acosix.alfresco.utility.core.repo.quartz1: Execution findbugs of goal org.codehaus.mojo:findbugs-maven-plugin:3.0.5:findbugs failed: Plugin org.codehaus.mojo:findbugs-maven-plugin:3.0.5 or one of its dependencies could not be resolved: Could not find artifact de.acosix.alfresco.maven:de.acosix.alfresco.maven.definitions:jar:1.3.4-SNAPSHOT in ossrh (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
[ERROR] 
`

is there anything i have to configure to get rid of this error?

Thanks,
Max

**Comment by AFaust** [comment]
I have recently started to adapt the various modules to ACS 7.0 and have not yet pushed any SNAPSHOT builds to OSSRH - that is why you cannot (yet) resolve that SNAPSHOT for utility.

**Comment by AFaust** [comment]
https://github.com/Acosix/alfresco-utility/commit/dffddf741d5217042c6c7832ad0e54cf01760483 on master addresses this issue by switching to the new parent POM version, which has been pushed to OSSRH.
