### ISSUE TITLE
Subject ignored for the acosix-mail action

### ISSUE THREAD

**Issue by douglascrp** [Acosix/alfresco-utility#15]
I noticed the action acosix-mail never uses the subject parameter.

I'm submitting a PR with the fix.

**Comment by AFaust** [comment]
I fixed it with commit https://github.com/Acosix/alfresco-utility/commit/484f931c1571bdf2387851af0f9065265f01e5dc before I even saw your issue and pull request. Sorry for not noticing and thus merging this from your contribution. Thanks nonetheless for using the feature and letting me know of the issue.
